// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Le8VI78-VONe6iD9oL6bmmOnkru1gaQ',
    appId: '1:371585623396:web:bfad96df477a53fda70671',
    messagingSenderId: '371585623396',
    projectId: 'ecotrade-119cc',
    authDomain: 'ecotrade-119cc.firebaseapp.com',
    storageBucket: 'ecotrade-119cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Y4koHoIwhiDGMJJMMjtGPkE8kH_KfDQ',
    appId: '1:371585623396:android:9d878dba529044a4a70671',
    messagingSenderId: '371585623396',
    projectId: 'ecotrade-119cc',
    storageBucket: 'ecotrade-119cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgpRRPg7U_hcfVE9kdjHdZq9ooNybG34U',
    appId: '1:371585623396:ios:6038ec598f51f672a70671',
    messagingSenderId: '371585623396',
    projectId: 'ecotrade-119cc',
    storageBucket: 'ecotrade-119cc.firebasestorage.app',
    iosBundleId: 'com.example.ecotrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgpRRPg7U_hcfVE9kdjHdZq9ooNybG34U',
    appId: '1:371585623396:ios:6038ec598f51f672a70671',
    messagingSenderId: '371585623396',
    projectId: 'ecotrade-119cc',
    storageBucket: 'ecotrade-119cc.firebasestorage.app',
    iosBundleId: 'com.example.ecotrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7Le8VI78-VONe6iD9oL6bmmOnkru1gaQ',
    appId: '1:371585623396:web:5fab08f3bf3439d3a70671',
    messagingSenderId: '371585623396',
    projectId: 'ecotrade-119cc',
    authDomain: 'ecotrade-119cc.firebaseapp.com',
    storageBucket: 'ecotrade-119cc.firebasestorage.app',
  );
}
